language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      env: TOXENV=py27
    - os: linux
      sudo: required
      python: 3.2
      env: TOXENV=py32
    - os: linux
      sudo: required
      python: 3.6
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py27
    - os: osx
      language: generic
      env: TOXENV=py36

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install pytest; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/hdf5@1.8; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export HDF5_DIR=$(brew --prefix homebrew/science/hdf5@1.8); fi
  # libhdf5-dev doesn't work in spite of https://github.com/travis-ci/apt-package-whitelist/issues/416
  # see also: https://github.com/travis-ci/apt-package-whitelist/issues/416
  # hmm, i don't like this but let's see what happens
  # right now this looks like the best HDF5 bet
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libhdf5-serial-dev; fi

install:
  # OSX needs this line
  - pip install -r requirements.txt

# extremely slow and fails pytest
# install:
#   - python setup.py install

script: pytest
