version: '2.1'
services:
  db:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
      - MYSQL_DATABASE=quilt
  pkg:
    image: quiltdata/server
    environment:
      - QUILT_SERVER_CONFIG=test_config.py
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_started
  s3:
    image: quiltdata/nginx-s3-proxy
    ports:
      - "5001:80"
  cli:
    image: quiltdata/cli
    environment:
      - QUILT_PKG_URL=http://pkg
      - QUILT_AUTH_URL=https://quilt-heroku.herokuapp.com
